# -*- coding: utf-8 -*-
"""VGG19 Recognize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UjcT7i2ANbQx20xMt4aWTSO3O2jJeHu
"""

!pip install tensorflow
from PIL import image
def display_img(pti):
  display(image.load_img(pti,color_mode='rgb',target_size=(224,224)))

x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
features = model.predict(x)
p = decode_predictions(features)
print(p[0][0][1])

img_path = "/content/airplane.jpeg"

setup = False
def init_vgg19():
  global setup, model
  if setup:
    pass
  else:
    from keras.applications.vgg19 import VGG19
    from tensorflow.keras.preprocessing import image
    from tensorflow.keras.applications.vgg16 import preprocess_input,decode_predictions
    from PIL import Image
    import numpy as np
    model = VGG19(weights = 'imagenet')
    setup = True

def vgg19_recognizeimage(image_path):
  global model
  init_vgg19()
  img = image.load_img(image_path,color_mode = 'rgb', target_size = (224,224))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)
  x = preprocess_input(x)
  features = model.predict(x)
  p = decode_predictions(features)
  return(p[0][0][1])

vgg19_recognizeimage(img_path)